-- MySQL Script generated by MySQL Workbench
-- Fri Nov 10 03:17:32 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bdsupreme2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdsupreme2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdsupreme2` DEFAULT CHARACTER SET utf8 ;
USE `bdsupreme2` ;

-- -----------------------------------------------------
-- Table `bdsupreme2`.`t_contas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsupreme2`.`t_contas` (
  `conta_codigo` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `conta_valor` DOUBLE NOT NULL,
  `conta_mesa` INT(10) NOT NULL,
  `conta_status` VARCHAR(20) NOT NULL,
  `conta_data` VARCHAR(10) NOT NULL,
  `conta_hora` VARCHAR(8) NOT NULL,
  `conta_cpf` VARCHAR(11) NULL DEFAULT NULL,
  PRIMARY KEY (`conta_codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdsupreme2`.`t_itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsupreme2`.`t_itens` (
  `itm_codigo` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `itm_nome` VARCHAR(100) NOT NULL,
  `itm_descricao` VARCHAR(200) NULL DEFAULT NULL,
  `itm_tipo` VARCHAR(50) NOT NULL,
  `itm_valor` DOUBLE UNSIGNED NOT NULL,
  `itm_status` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`itm_codigo`),
  UNIQUE INDEX `itm_codigo_UNIQUE` (`itm_codigo` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdsupreme2`.`t_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsupreme2`.`t_pedidos` (
  `ped_codigo` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ped_valor` DOUBLE NOT NULL,
  `ped_mesa` INT(11) NOT NULL,
  `ped_data` VARCHAR(10) NOT NULL,
  `ped_hora` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`ped_codigo`),
  UNIQUE INDEX `ped_codigo_UNIQUE` (`ped_codigo` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdsupreme2`.`t_pedido_itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsupreme2`.`t_pedido_itens` (
  `itm_codigo` INT(10) UNSIGNED NOT NULL,
  `ped_codigo` INT(10) UNSIGNED NOT NULL,
  `itm_qtde` INT(4) NOT NULL,
  `ped_status` VARCHAR(20) NOT NULL DEFAULT 'ABERTO',
  `ped_data` VARCHAR(10) NOT NULL,
  `ped_hora` VARCHAR(8) NOT NULL,
  INDEX `fk_t_pedido_itens_t_itens_idx` (`itm_codigo` ASC),
  INDEX `fk_t_pedido_itens_t_pedidos1_idx` (`ped_codigo` ASC),
  CONSTRAINT `fk_t_pedido_itens_t_itens`
    FOREIGN KEY (`itm_codigo`)
    REFERENCES `bdsupreme2`.`t_itens` (`itm_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_pedido_itens_t_pedidos1`
    FOREIGN KEY (`ped_codigo`)
    REFERENCES `bdsupreme2`.`t_pedidos` (`ped_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdsupreme2`.`t_pedidos_contas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsupreme2`.`t_pedidos_contas` (
  `ped_codigo` INT(10) UNSIGNED NOT NULL,
  `conta_codigo` INT(10) UNSIGNED NOT NULL,
  INDEX `fk_t_pedidos_contas_t_pedidos1_idx` (`ped_codigo` ASC),
  INDEX `fk_t_pedidos_contas_t_contas1_idx` (`conta_codigo` ASC),
  CONSTRAINT `fk_t_pedidos_contas_t_pedidos1`
    FOREIGN KEY (`ped_codigo`)
    REFERENCES `bdsupreme2`.`t_pedidos` (`ped_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_pedidos_contas_t_contas1`
    FOREIGN KEY (`conta_codigo`)
    REFERENCES `bdsupreme2`.`t_contas` (`conta_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdsupreme2`.`t_pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsupreme2`.`t_pessoas` (
  `pes_codigo` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `pes_nome` VARCHAR(100) NOT NULL,
  `pes_cpf` VARCHAR(11) NOT NULL,
  `pes_login` VARCHAR(100) NOT NULL,
  `pes_senha` VARCHAR(100) NOT NULL,
  `pes_tipo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`pes_codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
